# Generated by Django 3.2.4 on 2021-06-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('vaccinated', models.BooleanField(verbose_name='vaccinated')),
            ],
        ),
        migrations.CreateModel(
            name='Forestry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name='title')),
                ('name_of_owner', models.CharField(max_length=100, verbose_name='name_of_owner')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('population', models.IntegerField(verbose_name='population')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.animal')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(verbose_name='completed')),
                ('forestry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.forestry')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='feeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.feeder'),
        ),
    ]
